const escape = value => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const text = value => escape(value).replace(/(^|[\s>])(в|во|и|с|со|к|ко|о|об|на|по|из|за|не|а|у)\s+/gi, '$1$2&nbsp;');

export function renderReviewToggle(id) {
  return `<button class="review-toggle_component" type="button" data-review-toggle aria-expanded="false" aria-controls="${id}-full" hidden><span class="review-toggle_label">Подробнее</span><span class="review-toggle_icon" aria-hidden="true"></span></button>`;
}
export function renderReviewPanel(item, id) {
  return `<academy-review-panel class="review-panel_component"><p class="review-panel_quote" data-review-quote hidden>${text(item.quote)}</p><div class="review-panel_scroll" id="${id}-full" data-review-full data-slider-no-drag tabindex="0" role="region" aria-labelledby="${id}-author"><div class="review-panel_content"><div class="content-header_component review-panel_header"><h3 class="content-heading_component review-panel_author" id="${id}-author">${text(item.name)}</h3><p class="review-panel_role">${text(item.role)}</p></div><div>${item.paragraphs.map(p => `<p>${text(p)}</p>`).join('')}</div></div></div></academy-review-panel>`;
}
export function renderReviewCard(item, prefix, {responsive = false, icons = {play: "assets/icons/review-play.svg", pause: "assets/icons/review-pause.svg"}} = {}) {
  const id = `${prefix}-${item.id}`;
  const image = `<img class="review-card_image" src="${escape(item.image)}" width="${item.width || 507}" height="${item.height || 900}" alt="${escape(item.image_temporary ? 'Фотография из макета, временное изображение отзыва' : item.alt ?? (item.name || 'Кадр видеоотзыва студентки'))}" draggable="false" loading="lazy">`;
  const caption = item.lead || item.caption ? `<p class="review-card_caption">${text(item.lead)} <span class="review-card_caption-muted">${text(item.caption)}</span></p>` : '';
  if (item.type === 'quote') {
    const copy = item.name ? `<div class="content-header_component review-card_copy"><h3 class="content-heading_component is-card review-card_name">${text(item.name)}</h3>${caption}</div>` : caption;
    return `<div class="review-card_component is-quote${responsive ? ' is-responsive' : ''}" style="--review-image-position:${escape(item.position || 'center')}"><div class="review-card_media">${image}<div class="review-card_content"><blockquote class="review-panel_component review-panel_quote">${text(item.quote)}</blockquote></div></div>${copy}</div>`;
  }
  if (item.type === 'video') {
    const source = item.video?.src;
    const media = source ? `<video class="review-card_image" id="${id}-media" data-review-video src="${escape(source)}" poster="${escape(item.image)}" preload="none" playsinline controls aria-label="Видеоотзыв студентки" data-slider-no-drag></video>${image.replace('class="review-card_image"', 'class="review-card_image review-card_poster" data-review-video-poster hidden').replace(/alt="[^"]*"/, 'alt=""')}` : image;
    return `<academy-review class="review-card_component${responsive ? ' is-responsive' : ''}" data-review-video-card${source ? '' : ' data-video-preview'} style="--review-image-position:${escape(item.position)}"><div class="review-card_media">${media}<button class="review-control_component review-card_play" type="button" data-review-video-toggle${source ? ` aria-controls="${id}-media"` : ''} aria-label="Воспроизвести видеоотзыв${source ? '' : ' — предпросмотр'}" hidden><span class="review-card_play-glyph" aria-hidden="true"><img class="review-card_play-icon" src="${escape(icons.play)}" width="22" height="22" alt="" draggable="false"></span><span class="review-card_pause-glyph" aria-hidden="true"><img class="review-card_play-icon" src="${escape(icons.pause)}" width="22" height="22" alt="" draggable="false"></span></button><p class="review-card_status" data-review-video-status role="status" hidden></p></div>${caption}</academy-review>`;
  }
  return `<academy-review class="review-card_component${responsive ? ' is-responsive' : ''}" data-author="${escape(item.name)}" style="--review-image-position:${escape(item.position)}"><div class="review-card_media">${image}<div class="review-card_content">${renderReviewToggle(id)}${renderReviewPanel(item, id)}</div></div>${caption}</academy-review>`;
}
export function renderReviews(data) {
  const id = escape(data.id);
  return `<div class="reviews_component section-layout_component${data.responsive ? ' is-responsive' : ''}" data-slider-component><div class="reviews_header"><div class="section-header_component is-left${data.responsive ? ' is-responsive' : ''}"><h2 class="section-title_component is-left${data.responsive ? ' is-responsive' : ''}" id="${id}-heading">${text(data.title)}</h2></div><div class="reviews_controls"><button class="review-control_component is-previous" type="button" data-slider-previous aria-label="Предыдущие отзывы" aria-controls="${id}-slider" disabled><span class="review-control_icon" aria-hidden="true"></span></button><button class="review-control_component" type="button" data-slider-next aria-label="Следующие отзывы" aria-controls="${id}-slider" disabled><span class="review-control_icon" aria-hidden="true"></span></button></div></div><div class="reviews_slider splide" id="${id}-slider" data-academy-slider${data.responsive ? ' data-slider-all-widths' : ''} data-splide='{"focus":0,"omitEnd":true}' data-slider-label="Отзывы студентов" role="region" aria-labelledby="${id}-heading" tabindex="0"><div class="reviews_track splide__track"><ul class="reviews_list splide__list" role="list">${data.items.map(item => `<li class="reviews_slide splide__slide">${renderReviewCard(item, id, {responsive: data.responsive, icons: data.icons})}</li>`).join('')}</ul></div></div></div>`;
}
